### ISSUE TITLE
Feature Request: Reputation Circuit Breaker

### ISSUE THREAD

**Issue by 381e35** [MetricsDAO/labor-market#16]
In the original whitepaper a circuit breaker could not be modeled that achieved a circuit-breaker like function. With the progressive willingness of accepting model changes, Labor Markets _can now_ function with a circuit breaker (that carries radical parameter definition.)

What may not prove to be functional at the primitive level, but end up being a module that a exogenous builder can opt-in to. Historically, this has been incredibly difficult to achieve on-chain due to the requirement that one would have to balance the state of reputation somewhere in the network.

Whether that be on or off chain, the necessity of verification is constant and cannot be dissolved while maintaining the same levels of security. For Labor Markets, reputation is a limiting factor however it does completely rectify or prevent someone from being malicious.

To solve this, one could utilize a 24 hour (window adjustable) rolling average that reflects ones activate rate of contribution. Rather than just decay, the balance could constantly be reflective of only a certain amount of recent activity. While boiling in a bath of nuance, with the control of lacking interaction, while preemptive flipping of the breaker still is not possible, the breaker could be flipped when less than ideal situations have been reached.

In reality, this would result in a system that is much like the below (fake code)

```
def maintainer_status(networkParticipantAddress, operationsSeen, operationsDeclared):
  if networkParticipantAddress is not in operationsSeen:
    return HEALTHY
  min_work_required = operationsSeen[networkParticipantAddress] // MINIMUM_CONTRIBUTION_DENOMINATOR
  if min_work_required <= operationsDeclared[networkParticipantAddress] + THROTTLE_BUFFER:
    return HEALTHY
  elif min_work_required <= opsIncluded[networkParticipantAddress] + BAN_BUFFER:
    return THROTTLED
  return BANNED
```

With this model, the offering organization would expect every maintainer to process the enforcement of at least `min_work_required` or be removed from the maintaining system. If an individual falls behind, they are throttled and have limited ability to do anything beyond recover their reputation. (This optionally could be as the requirement to recover a deficit given they have slashed $xMETRIC) 

Further, the offering organization could implement `work schedules` that keeps an individual accountable Monday - Friday (with a minimum amount of delivered work) while offering Saturday and Sunday as a contribution-free day.

**This is an extremely experimental open issue and following PR. This should not be expected as a default function of Labor Markets.**

**Comment by masonchain** [comment]
"Will you close this, it got vetoed" - CHANCE
