### ISSUE TITLE
Integration of NBadgeAuth for access permissions.

### ISSUE THREAD

**Issue by 381e35** [MetricsDAO/labor-market#25]
This is still in the `Research` phase.

The functional (but not ideal) version can be found at: https://github.com/nftchance/n-badge
An experimental version can be found at: https://github.com/nftchance/remus

Neither version is ready to be ported into Labor Markets and requires further research.

**Comment by 381e35** [comment]
This is going to be a significant update -- @masonchain should we plan on building this as 1.7 even if app team goes from 1.6 -> 2.0 so that if they catch up to us they can implement N-Badge while we finalize economics?

**Comment by masonchain** [comment]
Yep, I think N-Badge is a very acceptable feature to roll out ASAP to get the front-end integrated.
