### ISSUE TITLE
Make getRewards a view function instead of a write function

### ISSUE THREAD

**Issue by thehannahlerman** [MetricsDAO/labor-market#33]
https://github.com/FlipsideCrypto/labor-market/blob/f6e85ffb0b7a815b4bbc27dbf4415ae9027850f3/src/enforcement/BucketEnforcement.sol#L174

We need to be able to do a contract read to find the rewards for a submission without having to go through the write flow

**Comment by 381e35** [comment]
Believe this was resolved but documenting for future readers that a write function can be retrieved as a view with a staticCall :)
